### ISSUE TITLE
Unable to pass custom port option into Docker

### ISSUE THREAD

**Issue by DessertOverlord** [dani3l0/Status#11]
This might just be my own stupidity (which if so, awesome, I get to learn something new) but when I attempt to add 

```
 environment:
      STATUS_SERVER_PORT: 9091
``` 
or
```
 environment:
      - STATUS_SERVER_PORT=9091
```

to the docker-compose.yml, I get a snippy response of 

```
status_app  | unhandled exception during asyncio.run() shutdown
status_app  | task: <Task finished name='Task-1' coro=<_run_app() done, defined at /usr/local/lib/python3.11/site-packages/aiohttp/web.py:289> exception=TypeError('The port is required to be int.')>
status_app  | Traceback (most recent call last):
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 516, in run_app
status_app  |     loop.run_until_complete(main_task)
status_app  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
status_app  |     return future.result()
status_app  |            ^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 418, in _run_app
status_app  |     names = sorted(str(s.name) for s in runner.sites)
status_app  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 418, in <genexpr>
status_app  |     names = sorted(str(s.name) for s in runner.sites)
status_app  |                        ^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_runner.py", line 114, in name
status_app  |     return str(URL.build(scheme=scheme, host=host, port=self._port))
status_app  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 237, in build
status_app  |     raise TypeError("The port is required to be int.")
status_app  | TypeError: The port is required to be int.
status_app  | Traceback (most recent call last):
status_app  |   File "/app/status.py", line 75, in <module>
status_app  |     web.run_app(app, host=config.get("server", "address"), port=config.get("server", "port"), ssl_context=ssl_context)
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 516, in run_app
status_app  |     loop.run_until_complete(main_task)
status_app  |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
status_app  |     return future.result()
status_app  |            ^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 418, in _run_app
status_app  |     names = sorted(str(s.name) for s in runner.sites)
status_app  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web.py", line 418, in <genexpr>
status_app  |     names = sorted(str(s.name) for s in runner.sites)
status_app  |                        ^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_runner.py", line 114, in name
status_app  |     return str(URL.build(scheme=scheme, host=host, port=self._port))
status_app  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
status_app  |   File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 237, in build
status_app  |     raise TypeError("The port is required to be int.")
status_app  | TypeError: The port is required to be int.
```

I figure there's just some input sanitation needed, as I'm probably one of the few morons who is trying to run this on a custom port through docker. Either that or I just don't know the proper syntax to pass an int through an environment variable to Docker.

**Comment by dani3l0** [comment]
Hi, sorry for slow response :/
I've just reproduced the bug and actually it seems like env variable converts integer variable 'port' to string one

**Comment by DessertOverlord** [comment]
No worries at all! And yeah I figured it had to be something weird like that going on

**Comment by dani3l0** [comment]
Okay, problem fixed, so I guess we can close the issue :)
