### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by wibe01204** [dani3l0/Status#9]
``` powershell
C:\Users\wibe0\OneDrive\桌面\新增資料夾 (2)\Status> python status.py
Traceback (most recent call last):
  File "C:\Users\wibe0\OneDrive\桌面\新增資料夾 (2)\Status\status.py", line 11, in <module>
    machine = Machine()
              ^^^^^^^^^
  File "C:\Users\wibe0\OneDrive\桌面\新增資料夾 (2)\Status\lib\machine\__init__.py", line 11, in __init__
    self.cpu = CPU()
               ^^^^^
  File "C:\Users\wibe0\OneDrive\桌面\新增資料夾 (2)\Status\lib\machine\cpu.py", line 27, in __init__
    cpu_info = self.get_cpu_info()
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wibe0\OneDrive\桌面\新增資料夾 (2)\Status\lib\machine\cpu.py", line 117, in get_cpu_info
    for line in cpu_info.split("\n"):
                ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'```

system : windows11
py : 3.11.5

**Comment by dani3l0** [comment]
Hey, there is one big problem in your setup:

> system : windows11

App heavily relies on directories like `/sys`, `/proc` which are provided by Linux Kernel and thus are not available on Windows. That's why Status does not and will not support Windows.

However, you can either **try running Status under WSL** (Windows Subsystem for Linux), there is a chance it might just work as WSL should provide directories mentioned directories.

**Comment by wibe01204** [comment]
OH! I get it!
Thanks~
